# Generated by Django 5.2 on 2025-04-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пакета')),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(verbose_name='Описание')),
                ('points', models.PositiveIntegerField(verbose_name='Количество баллов')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена (₽)')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
            options={
                'ordering': ['points'],
            },
        ),
    ]
