# Generated by Django 5.2 on 2025-04-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=20, unique=True, verbose_name='Password')),
                ('login', models.CharField(max_length=20, unique=True, verbose_name='login')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=65535, null=True, verbose_name='Description')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('university', models.CharField(blank=True, max_length=65535, null=True, verbose_name='University')),
                ('course', models.IntegerField(blank=True, null=True, verbose_name='Course')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Profile Photo')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online Status')),
                ('categories', models.ManyToManyField(blank=True, to='categories.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Helper',
                'verbose_name_plural': 'Helpers',
            },
        ),
    ]
