# Generated by Django 5.2 on 2025-04-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='Ваше описание', max_length=65535, null=True, verbose_name='Description')),
                ('rate', models.IntegerField(blank=True, default=5, null=True, verbose_name='Rating')),
                ('university', models.CharField(blank=True, default='', max_length=65535, null=True, verbose_name='Название университета')),
                ('course', models.IntegerField(blank=True, default=1, null=True, verbose_name='Course')),
                ('rank', models.IntegerField(blank=True, default=1, null=True, verbose_name='Rank')),
                ('is_mentor', models.BooleanField(default=False)),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Balance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Profile Photo')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online Status')),
                ('categories', models.ManyToManyField(blank=True, to='categories.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Additional info',
                'verbose_name_plural': 'Additional info',
            },
        ),
    ]
