# Generated by Django 5.2 on 2025-04-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=65535, null=True, verbose_name='Description')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('university', models.CharField(blank=True, max_length=65535, null=True, verbose_name='University')),
                ('course', models.IntegerField(blank=True, null=True, verbose_name='Course')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('categories', models.ManyToManyField(blank=True, to='categories.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Helper',
                'verbose_name_plural': 'Helpers',
            },
        ),
    ]
