# Generated by Django 5.1.7 on 2025-04-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='phone',
            field=models.CharField(default='+7 (XXX) XXX-XX-XX', max_length=15),
        ),
    ]
