# Generated by Django 5.2 on 2025-04-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_additionalinfo_delete_customuser_delete_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='user_id',
            field=models.IntegerField(default=-1),
        ),
    ]
