# Generated by Django 5.2 on 2025-04-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_additionalinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='rate',
            field=models.FloatField(blank=True, default=5.0, null=True, verbose_name='Rating'),
        ),
    ]
