# Generated by Django 5.1.7 on 2025-04-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_additionalinfo_delete_customuser_delete_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='rate',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='university',
            field=models.CharField(blank=True, max_length=65535, null=True, verbose_name='Название университета'),
        ),
    ]
