# Generated by Django 5.1.7 on 2025-04-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_additionalinfo_is_mentor_additionalinfo_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='course',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='description',
            field=models.TextField(blank=True, default='Ваше описание', max_length=65535, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='rank',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='university',
            field=models.CharField(blank=True, default='', max_length=65535, null=True, verbose_name='Название университета'),
        ),
    ]
